# Generated by Django 4.1 on 2022-08-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_list_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='auction_list',
            name='item_img_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='item_img_url', to='auctions.image_url'),
        ),
    ]
